### ISSUE TITLE
[1.11.2] Showing Black Hole Storage mod in JEI breaks mipmaps and causes flickering

### ISSUE THREAD

**Issue by chaNcharge** [APengu/BlackHoleStorage#1]
How to reproduce: 

1. Launch Minecraft with JEI and Black Hole Storage
2. Set mipmaps to any level other than 0 (most visible on level 4)
3. Open any world
4. Open your inventory, and in the JEI search bar, type "@ black" (without the space) to display all black hole storage items (or scroll down to the mod's item)
5. Close your inventory, and the mipmaps should be broken and flickering.

**Comment by APengu** [comment]
Uhh.... No ideas on that one yet

**Comment by MastrPancake** [comment]
This is a JEI problem not Black Hole Storage.
