### ISSUE TITLE
[1.12 Suggestion] Custom Recipes Atomic Transformer

### ISSUE THREAD

**Issue by MasterEnderman** [APengu/BlackHoleStorage#2]
Would it be possible to add custom recipes for the Atomic Transformer via a config or with CraftTweaker in the future?

**Comment by APengu** [comment]
it is, use hc-recipes folder for that

**Comment by MasterEnderman** [comment]
Is there any documentation how to add recipes?

also shouldn't the mod generate a config file, because the blckholestorage folder is empty?

**Comment by APengu** [comment]
I could send an example

**Comment by MasterEnderman** [comment]
I'm in you discord so you could pm me.

**Comment by APengu** [comment]
ok
